### ISSUE TITLE
Slowdown

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/ShowHandlesEverywhere#10]
macOS 10.12.6, G32.6.1 [1213] -- Does this plugin need an update for G2.6? When active with only two layers, only one glyph and nothing in the Background it really slows the app down. Only other plugins active are Angled Handles, Coordinates of Selected Nodes, and Stem Thickness.

**Comment by mekkablue** [comment]
It is true, the plug-in is somewhat deprecated. I recommend using the built-in _View > Show Nodes > In Background_ instead. I have taken it out of the Plugin Manager for now.
